name: 'Prepare CloudFront invalidation batch'
description: 'Prepare CloudFront invalidation batch, from S3 sync output'
branding:
  icon: box
  color: blue
inputs:
  sync-output:
    description: 'Output from AWS S3 sync'
    required: true
  s3-bucket:
    description: 'S3 bucket'
    required: true
  prefix:
    description: 'Prefix for invalidation paths'
    required: false
    default: ''
outputs:
  json:
    description: 'CloudFront invalidation batch, in JSON'
  json_escaped:
    description: 'CloudFront invalidation batch, in JSON, but escaped to be used as arguments in CLI commands'
  quantity:
    description: 'Quantity of paths to invalidate'
runs:
  using: 'node12'
  main: 'main.js'
